### ISSUE TITLE
Webapp not loading

### ISSUE THREAD

**Issue by upgundecha** [anataliocs/Exercise-files-full-stack-app-angular-spring-boot#16]
Web app is not loading after

```
ng serve
```

Observed some errors in console

![image](https://user-images.githubusercontent.com/1009929/27261424-41537454-5460-11e7-94ba-3b8430525480.png)

**Comment by upgundecha** [comment]
#17 should fix this

**Comment by anataliocs** [comment]
Hi @upgundecha I'm glad you're working through the course and I'm sorry you ran into an issue.

In **Chapter 2.1 Importing Dependencies using npm**

There is a section where we install the Twitter Bootstrap dependency using the [npm dependency manager](https://www.npmjs.com/).

https://www.lynda.com/Spring-Boot-tutorials/Generate-project-using-AngularJS-2-CLI-npm/573416/615261-4.html



> Next, let’s install Twitter Bootstrap 3 using npm.  Twitter Bootstrap is a grid-based UI component framework.  
>  
> It will provide us with some good-looking out-of-the-box UI components to use.  Don’t worry, prior knowledge of this framework is not necessary since we are just using the basic pre-built components.
>  
> npm install bootstrap@3
>  
> This command will install Twitter Bootstrap 3 in the following location:
> 
> /node_modules/bootstrap/

Please try running this npm command to install the Twitter Bootstrap dependency and let me know if you still have the problem:

`npm install bootstrap@3`

**Comment by upgundecha** [comment]
Aah..I missed this section. Thanks @anataliocs
